spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        driver_class: org.mariadb.Driver-class
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url:
    driver-class-name:
    username:
    password:
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB